// client/src/books/EnglishWord/utils/labels.ts

export function getGradeLabel(t: (k: string) => string, name?: string) {
    if (!name) return name || ''
    const map: Record<string, string> = {
        '幼稚园': 'englishword.grade.kindergarten',
        '小学3年级': 'englishword.grade.primary3',
        '小学4年级': 'englishword.grade.primary4',
        '小学5年级': 'englishword.grade.primary5',
        '小学6年级': 'englishword.grade.primary6',
        '中学1年级': 'englishword.grade.secondary1',
    }
    const key = map[name]
    return key ? t(key) : name
}

export function getGroupLabel(t: (k: string) => string, group?: string) {
    if (!group) return group || ''
    const map: Record<string, string> = {
        '颜色': 'englishword.group.color',
        '动物': 'englishword.group.animal',
        '水果': 'englishword.group.fruit',
        '蔬菜': 'englishword.group.vegetable',
        '数字': 'englishword.group.number',
        '身体': 'englishword.group.body',
        '身体部位': 'englishword.group.bodyParts',
        '家庭': 'englishword.group.family',
        '家庭成员': 'englishword.group.familyMembers',
        '食物': 'englishword.group.food',
        '衣服': 'englishword.group.clothes',
        '服饰': 'englishword.group.clothing',
        '学校': 'englishword.group.school',
        '天气': 'englishword.group.weather',
        '交通': 'englishword.group.transport',
        '交通工具': 'englishword.group.vehicles',
        '形状': 'englishword.group.shape',
        '颜色与形状': 'englishword.group.colorAndShape',
        '人物': 'englishword.group.people',
        '礼貌用语': 'englishword.group.politeExpressions',
        '饮品主食': 'englishword.group.drinksStaples',
        '农场动物': 'englishword.group.farmAnimals',
        '野生动物': 'englishword.group.wildAnimals',
        '家居家具': 'englishword.group.homeFurniture',
        '天象天气': 'englishword.group.weatherPhenomena',
        '时间时段': 'englishword.group.timePeriods',
        '玩具': 'englishword.group.toys',
        '游乐设施': 'englishword.group.playgroundFacilities',
        '家居用品': 'englishword.group.householdItems',
        '洗护用品': 'englishword.group.toiletries',
        '校园场所': 'englishword.group.schoolPlaces',
        '校园人物': 'englishword.group.schoolPeople',
        '文具': 'englishword.group.stationery',
        '校园家具': 'englishword.group.schoolFurniture',
        '教具': 'englishword.group.teachingAids',
        '自然景物': 'englishword.group.naturalScenery',
        '四季': 'englishword.group.seasons',
        '月份': 'englishword.group.months',
        '星期': 'englishword.group.weekdays',
        '动作动词': 'englishword.group.actionVerbs',
        '方位介词': 'englishword.group.positionPrepositions',
        '情绪形容词': 'englishword.group.emotionAdjectives',
        '职业': 'englishword.group.jobs',
        '节日场景': 'englishword.group.festivalScenes',
        '生活场所': 'englishword.group.livingPlaces',
        '场所': 'englishword.group.place',
        '教室物品': 'englishword.group.classroomItems',
        '饮品': 'englishword.group.beverages',
        '家居物品': 'englishword.group.homeItems',
        '形容词': 'englishword.group.adjective',
        '介词': 'englishword.group.preposition',
        '天象': 'englishword.group.heavenlyPhenomena',
        '时间': 'englishword.group.time',
        '物品': 'englishword.group.object',
        '应答词': 'englishword.group.responseWords',
        '系动词': 'englishword.group.linkingVerb',
        '动词': 'englishword.group.verb',
        '名词': 'englishword.group.noun',
        '集合名词': 'englishword.group.collectiveNoun',
        '房间部件': 'englishword.group.roomParts',
        '电器': 'englishword.group.electricalAppliance',
        '日用品': 'englishword.group.dailyNecessities',
        '运动器材': 'englishword.group.sportsEquipment',
        '收藏品': 'englishword.group.collectible',
        '个人描述': 'englishword.group.personalDescription',
        '日常活动': 'englishword.group.dailyActivities',
        '植物部位': 'englishword.group.plantParts',
        '昆虫': 'englishword.group.insect',
        '鸟类': 'englishword.group.bird',
        '水生动物': 'englishword.group.aquaticAnimal',
        '陆生小动物': 'englishword.group.landSmallAnimal',
        '坚果': 'englishword.group.nut',
        '果蔬': 'englishword.group.fruitVegetable',
        '肉类': 'englishword.group.meat',
        '水产食材': 'englishword.group.seafoodIngredient',
        '乳制品': 'englishword.group.dairyProduct',
        '甜调味料': 'englishword.group.sweetSeasoning',
        '调味品': 'englishword.group.condiment',
        '厨房用品': 'englishword.group.kitchenUtensil',
        '厨房电器': 'englishword.group.kitchenAppliance',
        '卧室家具': 'englishword.group.bedroomFurniture',
        '卧室用品': 'englishword.group.bedroomSupplies',
        '家居软装': 'englishword.group.homeSoftDecoration',
        '配饰': 'englishword.group.accessory',
        '箱包': 'englishword.group.bagLuggage',
        '道路设施': 'englishword.group.roadFacility',
        '公共场所': 'englishword.group.publicPlace',
        '商铺': 'englishword.group.shopStore',
        '美术工具': 'englishword.group.artTool',
        '教学工具': 'englishword.group.teachingTool',
        '书本': 'englishword.group.book',
        '读物': 'englishword.group.readingMaterial',
        '学校设施': 'englishword.group.schoolFacility',
        '体育器材': 'englishword.group.sportsGear',
        '体育配饰': 'englishword.group.sportsAccessory',
        '超级角色': 'englishword.group.superCharacter',
        '副词': 'englishword.group.adverb',
        '方位副词': 'englishword.group.adverbOfPlace',
        '连接副词': 'englishword.group.conjunctiveAdverb',
    }
    const key = map[group]
    return key ? t(key) : group
}