name = "openedu-worker"
main = "src/index.js"
compatibility_date = "2026-10-02"

[vars]
FRONTEND_URL = "https://d83667c7.openedu-client.pages.dev"
SUPABASE_URL = "https://txeehcnulkamrzaribym.supabase.co"